import environ

# ENVIRON
PROJECT_ROOT = environ.Path(__file__) - 2
PROJECT_ROOT.file('.env.development')
env = environ.Env()
env.read_env(PROJECT_ROOT('.env.development'))


SECRET_KEY = env('SECRET_KEY')


DEBUG = True

ALLOWED_HOSTS = ['*']


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_PASSWORD')

AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_IMAGE_URL = env('AWS_IMAGE_URL')


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
        'NAME': env('DATABASE_NAME'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4'
        }
    }
}

MONGO_USER = env('MONGO_USER')
MONGO_PASSWORD = env('MONGO_PASSWORD')
MONGO_HOST = env('MONGO_HOST')


ONESIGNAL_API_KEY = env('ONESIGNAL_API_KEY')
ONESIGNAL_APP_ID = env('ONESIGNAL_APP_ID')

FACEBOOK_APP_ID = env('FACEBOOK_APP_ID')
FACEBOOK_APP_SECRET = env('FACEBOOK_APP_SECRET')

GOOGLE_OAUTH2_CLIENT_ID = env('GOOGLE_OAUTH2_CLIENT_ID')

SOCIAL_AUTH_APPLE_TEAM_ID = env('SOCIAL_AUTH_APPLE_TEAM_ID')
SOCIAL_AUTH_APPLE_KEY_ID = env('SOCIAL_AUTH_APPLE_KEY_ID')
SOCIAL_AUTH_APPLE_PRIVATE_KEY = '''-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMy2FOysZ9Q99njYF
/aYZE+UIGwowWXPTj/fyXc0ae6ugCgYIKoZIzj0DAQehRANCAASiGEs6tkOasTkz
/JXPwaTcxeztXZh2NQPlpBSWNdl6g62fyODNY6ke8LgZhBmW6rExHRaucaWhMcVX
JOmnjeYS
-----END PRIVATE KEY-----'''
CLIENT_ID = env('CLIENT_ID')
